version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: gatsby-plugin-netlify
    versions:
    - 3.0.1
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 2.11.0
    - 2.12.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-page-creator
    versions:
    - 2.10.0
    - 2.10.1
    - 2.9.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-postcss
    versions:
    - 3.6.0
    - 3.7.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-preload-fonts
    versions:
    - 1.8.0
    - 1.9.0
    - 1.9.1
    - 2.1.0
    - 2.2.0
    - 2.3.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.13.3
    - 2.13.4
    - 2.14.0
    - 2.14.1
    - 2.14.2
    - 2.14.3
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.11.0
    - 2.12.0
    - 2.12.1
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 3.12.0
    - 3.13.0
    - 4.1.0
    - 4.2.0
    - 5.0.0
  - dependency-name: gatsby-plugin-styled-components
    versions:
    - 3.10.0
    - 3.9.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby
    versions:
    - 2.31.1
    - 2.32.0
    - 2.32.10
    - 2.32.11
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: prismjs
    versions:
    - 1.23.0
  - dependency-name: socket.io
    versions:
    - 2.4.1
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
  - dependency-name: object-path
    versions:
    - 0.11.5
