import Head from 'next/head';
import Uses from '../components/Uses';

const UsesPage = () => (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Uses />
    </div>
  );


export default UsesPage;
